apiVersion: v1
kind: Secret
metadata:
  name: ai-task-secrets
  namespace: ai-task-platform
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb-service:27017/ai_task_db"
  REDIS_URL: "redis://redis-service:6379"
  JWT_SECRET: "k8s_super_secure_production_jwt_secret_key_2026"
